/** A file with all the static details because they barely change */
import { Detail, DetailType, TeacherDetail } from "@/classes/details";

export const classes = [
    new Detail(DetailType.Class, "UK", "P1.A"),
    new Detail(DetailType.Class, "UL", "P1.B"),
    new Detail(DetailType.Class, "UM", "T1.C"),
    new Detail(DetailType.Class, "UG", "P2.A"),
    new Detail(DetailType.Class, "UI", "P2.B"),
    new Detail(DetailType.Class, "UJ", "T2.C"),
    new Detail(DetailType.Class, "UD", "P3.A"),
    new Detail(DetailType.Class, "UE", "P3.B"),
    new Detail(DetailType.Class, "UF", "T3.C"),
    new Detail(DetailType.Class, "UA", "P4.A"),
    new Detail(DetailType.Class, "UB", "P4.B"),
    new Detail(DetailType.Class, "UC", "T4.C")
];

export const teachers = [
    new TeacherDetail("U0030", "Antoš Petr", "An"),
    new TeacherDetail("UXYPY", "Bečvářová Hana", "Be"),
    new TeacherDetail("UKYOM", "Bláhová Ludmila", "Bh"),
    new TeacherDetail("UWYPV", "Dvořáková Lenka", "Dv"),
    new TeacherDetail("U30J8", "Fiala Libor", "Fi"),
    new TeacherDetail("UZYNS", "Filip Petr", "Fp"),
    new TeacherDetail("URYP4", "Fučíková Jana", "Fu"),
    new TeacherDetail("UKYOL", "Hromádko Přemysl", "Hm"),
    new TeacherDetail("ULYOS", "Ivon Pavel", "Iv"),
    new TeacherDetail("UTYP8", "Jurčeková Martina", "Ju"),
    new TeacherDetail("UVYPO", "Jurčík Martin", "Jí"),
    new TeacherDetail("UXYPX", "Kalivoda Jonáš", "Kl"),
    new TeacherDetail("U0011", "Klein Ivan", "Kn"),
    new TeacherDetail("U0025", "Kleinová Radka", "Ká"),
    new TeacherDetail("UQYOY", "Korovin Vsevolod", "Kv"),
    new TeacherDetail("U0037", "Kratochvíl Aleš", "Kt"),
    new TeacherDetail("UZYNH", "Mašek Petr", "Ma"),
    new TeacherDetail("UYGLD", "Megvinet Ivana", "Me"),
    new TeacherDetail("UXYPW", "Mrkáček Vladimír", "Mk"),
    new TeacherDetail("UXYQ2", "Müller Vojtěch", "Ml"),
    new TeacherDetail("UXYQ1", "Nebehay Martin", "Nb"),
    new TeacherDetail("UXYQ4", "Noska Pavel", "Ns"),
    new TeacherDetail("UXYQ0", "Oktábec Marek", "Ok"),
    new TeacherDetail("UQYP2", "Pelikánová Zdeňka", "Pe"),
    new TeacherDetail("UUYPM", "Pícha Miloš", "Pí"),
    new TeacherDetail("UZ2TE", "Šafránková Hana", "Ša"),
    new TeacherDetail("ULYOP", "Šibrava Ondřej", "Šb"),
    new TeacherDetail("URYP5", "Strnka Richard", "St"),
    new TeacherDetail("UVYPP", "Vaněček Ondřej", "Va"),
    new TeacherDetail("U0001", "Vodička Martin", "Vo"),
    new TeacherDetail("UZYNE", "Vostárek Tomáš", "Vs"),
    new TeacherDetail("UWYPU", "Westfál David", "We"),
    new TeacherDetail("UTYPB", "Zikán Jiří", "Zk")
];

export const rooms = [
    new Detail(DetailType.Room, "U2", "01"),
    new Detail(DetailType.Room, "GZ", "02"),
    new Detail(DetailType.Room, "A5", "03"),
    new Detail(DetailType.Room, "IZ", "06"),
    new Detail(DetailType.Room, "6B", "102"),
    new Detail(DetailType.Room, "35", "103"),
    new Detail(DetailType.Room, "OG", "104"),
    new Detail(DetailType.Room, "VF", "107"),
    new Detail(DetailType.Room, "LG", "108"),
    new Detail(DetailType.Room, "FO", "109"),
    new Detail(DetailType.Room, "00", "114"),
    new Detail(DetailType.Room, "30", "115"),
    new Detail(DetailType.Room, "ZZ", "116"),
    new Detail(DetailType.Room, "9A", "202"),
    new Detail(DetailType.Room, "84", "203"),
    new Detail(DetailType.Room, "51", "204"),
    new Detail(DetailType.Room, "C0", "208"),
    new Detail(DetailType.Room, "N5", "209"),
    new Detail(DetailType.Room, "DT", "210"),
    new Detail(DetailType.Room, "32", "211"),
    new Detail(DetailType.Room, "ZX", "213"),
    new Detail(DetailType.Room, "G0", "214"),
    new Detail(DetailType.Room, "T0", "TĚL")
];
