/** A file with all the static details because they barely change */
import { Detail, DetailType, TeacherDetail } from "@/classes/details/details";

export const classes = [
    new Detail(DetailType.Class, "UK", "P1.A"),
    new Detail(DetailType.Class, "UL", "P1.B"),
    new Detail(DetailType.Class, "UM", "T1.C"),
    new Detail(DetailType.Class, "UG", "P2.A"),
    new Detail(DetailType.Class, "UI", "P2.B"),
    new Detail(DetailType.Class, "UJ", "T2.C"),
    new Detail(DetailType.Class, "UD", "P3.A"),
    new Detail(DetailType.Class, "UE", "P3.B"),
    new Detail(DetailType.Class, "UF", "T3.C"),
    new Detail(DetailType.Class, "UA", "P4.A"),
    new Detail(DetailType.Class, "UB", "P4.B"),
    new Detail(DetailType.Class, "UC", "T4.C")
];

export const teachers = [
    new TeacherDetail("U0030", "An", "Petr Antoš", "antos", "Ing"),
    new TeacherDetail("UXYPY", "Be", "Hana Bečvářová", "becvarova", "Mgr"),
    new TeacherDetail("UKYOM", "Bh", "Ludmila Bláhová", "blahova", "Mgr"),
    new TeacherDetail("UWYPV", "Dv", "Lenka Dvořáková", "dvorakova", "Mgr"),
    new TeacherDetail("U30J8", "Fi", "Libor Fiala", "fiala", "Mgr"),
    new TeacherDetail("UZYNS", "Fp", "Petr Filip", "filip", "Mgr"),
    new TeacherDetail("URYP4", "Fu", "Jana Fučíková", "fucikova", "Ing", "PhD"),
    new TeacherDetail("UKYOL", "Hm", "Přemysl Hromádko", "hromadko", "Mgr"),
    new TeacherDetail("ULYOS", "Iv", "Pavel Ivon", "ivon", "Ing"),
    new TeacherDetail("UTYP8", "Ju", "Martina Jurčeková", "jurcekova", "PhDr"),
    new TeacherDetail("UVYPO", "Jí", "Martin Jurčík", "jurcik", "Bc"),
    new TeacherDetail("UXYPX", "Kl", "Jonáš Kalivoda", "kalivoda", "Bc"),
    new TeacherDetail("U0011", "Kn", "Ivan Klein", "klein", "Mgr"),
    new TeacherDetail("U0025", "Ká", "Radka Kleinová", "kleinova", "Mgr"),
    new TeacherDetail("UQYOY", "Kv", "Vsevolod Korovin", "korovin", "MgA"),
    new TeacherDetail("U0037", "Kt", "Aleš Kratochvíl", "kratochvil", "Ing"),
    new TeacherDetail("UZYNH", "Ma", "Petr Mašek", "masek", "Mgr"),
    new TeacherDetail("UYGLD", "Me", "Ivana Megvinet", "megvinet", "PaedDr"),
    new TeacherDetail("UXYPW", "Mk", "Vladimír Mrkáček", "mrkacek"),
    new TeacherDetail("UXYQ2", "Ml", "Vojtěch Müller", "muller"),
    new TeacherDetail("UXYQ1", "Nb", "Martin Nebehay", "nebehay"),
    new TeacherDetail("UXYQ4", "Ns", "Pavel Noska", "noska", "Mgr"),
    new TeacherDetail("UXYQ0", "Ok", "Marek Oktábec", "oktabec", "Bc"),
    new TeacherDetail("UQYP2", "Pe", "Zdeňka Pelikánová", "pelikanova", "Mgr"),
    new TeacherDetail("UUYPM", "Pí", "Miloš Pícha", "picha", "Mgr", "MBA"),
    new TeacherDetail("UZ2TE", "Ša", "Hana Šafránková", "safrankova", "Mgr"),
    new TeacherDetail("ULYOP", "Šb", "Ondřej Šibrava", "sibrava", "Ing"),
    new TeacherDetail("URYP5", "St", "Richard Strnka", "strnka", "Ing"),
    new TeacherDetail("UVYPP", "Va", "Ondřej Vaněček", "vanecek", "Mgr"),
    new TeacherDetail("U0001", "Vo", "Martin Vodička", "vodicka", "Ing"),
    new TeacherDetail("UZYNE", "Vs", "Tomáš Vostárek", "vostarek", "Mgr"),
    new TeacherDetail("UWYPU", "We", "David Westfál", "westfal", "Bc"),
    new TeacherDetail("UTYPB", "Zk", "Jiří Zikán", "zikan", "Ing")
];

export const rooms = [
    new Detail(DetailType.Room, "U2", "01"),
    new Detail(DetailType.Room, "GZ", "02"),
    new Detail(DetailType.Room, "A5", "03"),
    new Detail(DetailType.Room, "IZ", "06"),
    new Detail(DetailType.Room, "6B", "102"),
    new Detail(DetailType.Room, "35", "103"),
    new Detail(DetailType.Room, "OG", "104"),
    new Detail(DetailType.Room, "VF", "107"),
    new Detail(DetailType.Room, "LG", "108"),
    new Detail(DetailType.Room, "FO", "109"),
    new Detail(DetailType.Room, "00", "114"),
    new Detail(DetailType.Room, "30", "115"),
    new Detail(DetailType.Room, "ZZ", "116"),
    new Detail(DetailType.Room, "9A", "202"),
    new Detail(DetailType.Room, "84", "203"),
    new Detail(DetailType.Room, "51", "204"),
    new Detail(DetailType.Room, "C0", "208"),
    new Detail(DetailType.Room, "N5", "209"),
    new Detail(DetailType.Room, "DT", "210"),
    new Detail(DetailType.Room, "32", "211"),
    new Detail(DetailType.Room, "ZX", "213"),
    new Detail(DetailType.Room, "G0", "214"),
    new Detail(DetailType.Room, "T0", "TĚL")
];
