version: "3.8"

name: schedule

services:
    schedule:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        restart: always
        ports:
            - "3000:3000"
        volumes:
            # This prevents the cache from being invalidated when the Dockerfile changes
            - ../data.bson:/app/data.bson
