version: "3.8"

services:
    schedule:
        build:
            args:
                PROXY: socks5://tor:9050
        restart: always
        ports:
            - "3000:3000"
    tor:
        image: dperson/torproxy
        restart: always
